version: "3.9"
services:
  reddit-pipeline:
    build: microservices/reddit_data_ingestion/
    env_file:
      - microservices/reddit_data_ingestion/.reddit.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - velkozz_web_api_velkozz-api-network
  
  social-media-quant-pipeline:
    build: microservices/social_media_quant_ingestion/
    env_file: 
      - microservices/social_media_quant_ingestion/.quant.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - velkozz_web_api_velkozz-api-network      

  daily-youtube-channel-stats-pipeline:
    build: microservices/youtube_data_ingestion/
    env_file:
      - microservices/youtube_data_ingestion/.youtubb.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - velkozz_web_api_velkozz-api-network

#  indeed-job-listings-pipeline:
#    build: microservices/indeed_data_ingestion/
#    env_file: 
#      - microservices/indeed_data_ingestion/.indeed.env
#    environment: 
#      - PYTHONUNBUFFERED=1
#    networks:
#      - velkozz_web_api_velkozz-api-network      


networks:
  velkozz_web_api_velkozz-api-network:
    external: true
